services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: go_app
    ports:
      - "3006:3006"
    volumes:
      - ../dumpFiles:/app/docker_dumpFiles   # Partage pour stocker les dumps localement
      - ../templates:/app/templates

    depends_on:
      - safebase
      - apple
      - blizzard
      - huawey

  # Base de données PostgreSQL principale
  safebase:
    image: postgres:15
    container_name: safebase
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: safebase
    ports:
      - "5432:5432"
    volumes:
      - safebase_data:/var/lib/postgresql/data  # Volume pour la persistance des données
      - dumpFiles:/shared_data  # Volume partagé pour les dumps

  # Autres bases PostgreSQL
  apple:
    image: postgres:15
    container_name: apple
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: apple
    ports:
      - "5433:5432"
    volumes:
      - apple_data:/var/lib/postgresql/data  # Volume pour la persistance des données
      - dumpFiles:/shared_data  # Volume partagé pour les dumps

  blizzard:
    image: postgres:15
    container_name: blizzard
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: blizzard
    ports:
      - "5434:5432"
    volumes:
      - blizzard_data:/var/lib/postgresql/data  # Volume pour la persistance des données
      - dumpFiles:/shared_data  # Volume partagé pour les dumps

  # Base de données MySQL
  huawey:
    image: mysql:8
    container_name: huawey
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: huawey
      MYSQL_USER: admin
      MYSQL_PASSWORD: securepassword
    ports:
      - "3306:3306"
    volumes:
      - huawey_data:/var/lib/mysql  # Volume pour la persistance des données
      - dumpFiles:/shared_data  # Volume partagé pour les dumps

volumes:
  safebase_data:  # Volume persistant pour la base de données safebase
  apple_data:     # Volume persistant pour la base de données apple
  blizzard_data:  # Volume persistant pour la base de données blizzard
  huawey_data:    # Volume persistant pour la base de données huawey
  templates:      
  dumpFiles:      # Volume partagé pour les dumps
