services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile  # Nom du Dockerfile
    container_name: go_app
    ports:
      - "3006:3006"
    volumes:
      - dumpFiles:/app/docker_dumpFiles   # Volume pour stocker les dumps
    depends_on:
      - safebase
      - apple
      - blizzard
      - huawey

  # Base de données PostgreSQL principale
  safebase:
    image: postgres:15
    container_name: safebase
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: safebase
    ports:
      - "5432:5432"
    volumes:
      - safebase_data:/var/lib/postgresql/data

  # Autres bases PostgreSQL
  apple:
    image: postgres:15
    container_name: apple
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: apple
    ports:
      - "5433:5432"
    volumes:
      - apple_data:/var/lib/postgresql/data"

  blizzard:
    image: postgres:15
    container_name: blizzard
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: blizzard
    ports:
      - "5434:5432"
    volumes:
      - blizzard_data:/var/lib/postgresql/data"

  # Base de données MySQL
  huawey:
    image: mysql:8
    container_name: huawey
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: huawey
      MYSQL_USER: admin
      MYSQL_PASSWORD: securepassword
    ports:
      - "3306:3306"
    volumes:
      - huawey_data:/var/lib/mysql"

volumes:
  safebase_data:
  huawey_data:
  apple_data:
  blizzard_data:
  dumpFiles:
