services:
  safebase:
    image: postgres:15
    container_name: safebase
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: safebase
    ports:
      - "5432:5432"
    volumes:
      - safebase_data:/var/lib/postgresql/data
      # - dumpFiles:/backups  
      - dumpFiles:/docker_dumpFiles  


  apple:
    image: postgres:15
    container_name: apple
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: apple
    ports:
      - "5433:5432"
    volumes:
      - apple_data:/var/lib/postgresql/data
      - dumpFiles:/backups  

  blizzard:
    image: postgres:15
    container_name: blizzard
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: blizzard
    ports:
      - "5434:5432"
    volumes:
      - blizzard_data:/var/lib/postgresql/data
      - dumpFiles:/backups  

  huawey:
    image: mysql:8
    container_name: huawey
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: huawey
      MYSQL_USER: admin
      MYSQL_PASSWORD: securepassword
    ports:
      - "3306:3306"
    volumes:
      - huawey_data:/var/lib/mysql
      - dumpFiles:/backups  

volumes:
  safebase_data:
  huawey_data:
  apple_data:
  blizzard_data:
  dumpFiles:
